#! /usr/bin/env sh
accountId=451285781526 # 443263291755 for schedule service
creds=$(curl -s -L -c ~/.midway/cookie -b ~/.midway/cookie -X POST -H "Accept: application/json" -d "{\"awsAccountId\":\"$accountId\", \"awsPartition\": \"aws\", \"duration\":3600}" https://iibs-midway.corp.amazon.com/GetSecurityTokenByAccount)
export AWS_SECRET_ACCESS_KEY=$(echo $creds | jq -r ".secretAccessKey")
export AWS_ACCESS_KEY_ID=$(echo $creds | jq -r ".accessKeyId")
export AWS_SESSION_TOKEN=$(echo $creds | jq -r ".sessionToken")
export AWS_REGION=us-west-2
export AWS_DEFAULT_REGION=us-west-2
aws sts get-caller-identity
