#! /usr/bin/env bash

cd "$HOME/.local/src/vim" || exit 1


CFLAGS=-O3 \
	./configure \
	--enable-multibyte \
	--enable-terminal \
	--enable-pythoninterp=dynamic \
	--enable-python3interp \
	--with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu \
	--with-python3-config-dir=/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu \
	--enable-cscope \
	--enable-gui=auto \
	--with-features=huge \
	--with-x \
	--enable-fontset \
	--enable-largefile \
	--disable-netbeans \
	--with-compiledby="Marcus Karpoff" \
	--enable-fail-if-missing \
	--prefix=$HOME/.local/
#--enable-rubyinterp=dynamic \
#--with-ruby-command=/usr/local/bin/ruby \
#--enable-perlinterp=dynamic \
#--enable-luainterp \
#--with-luajit \
rc=$?

if [[ $rc != 0 ]]; then
	echo "#################################"
	echo "######## BUILD FAILED ###########"
	echo "#################################"
	exit $rc
else
	echo "#################################"
	echo "######## BUILD SUCCESS ##########"
	echo "#################################"
fi


make -j
rc=$?

if [[ $rc != 0 ]]; then
	echo "#################################"
	echo "######## BUILD FAILED ###########"
	echo "#################################"
	exit $rc
else
	echo "#################################"
	echo "######## BUILD SUCCESS ##########"
	echo "#################################"
fi

make install
rc=$?

if [[ $rc != 0 ]]; then
	echo "#################################"
	echo "######## BUILD FAILED ###########"
	echo "#################################"
	exit $rc
else
	echo "#################################"
	echo "######## BUILD SUCCESS ##########"
	echo "#################################"
fi
