#! /usr/bin/env bash

cd "$HOME/.local/src/vim" || exit 1


./configure \
--prefix="$HOME/.local/" \
--enable-multibyte \
--enable-terminal \
--enable-pythoninterp=dynamic \
--with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu \
--enable-python3interp \
--with-python3-config-dir=/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu \
--enable-cscope \
--enable-gui=auto \
--with-features=huge \
--with-x \
--enable-fontset \
--enable-largefile \
--disable-netbeans \
--with-compiledby="Marcus Karpoff" \
--enable-fail-if-missing
#--enable-rubyinterp=dynamic \
#--with-ruby-command=/usr/local/bin/ruby \
#--enable-perlinterp=dynamic \
#--enable-luainterp \
#--with-luajit \

make install -j 16
rc=$?

if [[ $rc != 0 ]]; then
	echo "#################################"
	echo "######## BUILD FAILED ###########"
	echo "#################################"
else
	echo "#################################"
	echo "######## BUILD SUCCESS ##########"
	echo "#################################"
fi
