#!/bin/bash
# Prompt function because PROMPT_COMMAND is awesome

function set_powerline_prompt() {
	local RA REDF BLKF BLKB GREF GREB YELF YELB PRPF PRPB BLUF BLUB GRYF GRYB
	local usrin branch venv path ps1a ps1b non_mono_used
	RA=''
	LA=''
	non_mono_used=$((0))
	DIRTY_SYM='✗'
	CLEAN_SYM='✓'
	STASH_SYM='☇'
	AHEAD_SYM='↑'
	BHIND_SYM='↓'

	BLKF="\\[$(tput setaf  0)\\]"
	BLKB="\\[$(tput setab  0)\\]"
	REDF="\\[$(tput setaf  1)\\]"
	GREF="\\[$(tput setaf  2)\\]"
	GREB="\\[$(tput setab  2)\\]"
	YELF="\\[$(tput setaf  3)\\]"
	YELB="\\[$(tput setab  3)\\]"
	BLUF="\\[$(tput setaf  4)\\]"
	BLUB="\\[$(tput setab  4)\\]"
	PRPF="\\[$(tput setaf  5)\\]"
	PRPB="\\[$(tput setab  5)\\]"
	GRYF="\\[$(tput setaf  8)\\]"
	GRYB="\\[$(tput setab  8)\\]"

	# Display Username
	usrin="${GREB}${BLKF} \\h  ${GREF}"

	# GIT STUFF
	if [ -d .git ] || git rev-parse --get-dir > /dev/null 2>&1
	then
		local _ahead _behind _dirty _branch _stash _status
		_ahead=$(git rev-list "@{u}..HEAD" | wc -l)
		_behind=$(git rev-list "HEAD..@{u}" | wc -l)
		_stash=$(git stash list | wc -l)
		_dirty=$(git status --porcelain | wc -l)
		_branch=$(git symbolic-ref HEAD 2>/dev/null)
		_status=${_branch#refs/heads/} # apparently faster than sed
		if (( _dirty > 0 ))
		then
			_status="$_status${REDF} $_dirty${DIRTY_SYM} "
			non_mono_used=$((non_mono_used + 1))
		else
			_status="$_status${GREF}${CLEAN_SYM} "
			non_mono_used=$((non_mono_used + 1))
		fi
		if (( _stash > 0 )); then
			_status="$_status${_stash}${STASH_SYM}"
			non_mono_used=$((non_mono_used + 1))
		fi
		if (( _ahead > 0 )); then 
			_status="$_status${_ahead}${AHEAD_SYM}"
		fi
		if (( _behind > 0 )); then
			_status="$_status${_behind}${BHIND_SYM}"
		fi
		branch="${YELB}${RA}${BLKF} ${_status} ${YELF}"
	else
		branch=""
	fi

	# Virtual Env stuff
	if [[ $VIRTUAL_ENV != "" ]]; then
		local _venv=${VIRTUAL_ENV##*/}
		venv="${PRPB}${RA}${BLKF} ${_venv}  ${PRPF}"
	else
		venv=""
	fi

	path="${BLUB}${RA}${BLKF} \\w ${BLUF}"
	clock="${GREF}${BLKB}${LA}${GREB}${BLKF} \\@"
	ps1_1_l="\\[$(tput hpa 0)\\]${GRYF}${GRYB} ${GREB}${RA}${usrin}${branch}${venv}${path} ${BLKB}${RA} "
	ps1_1_r="\\[$(tput hpa $(($(tput cols) - 15 - non_mono_used)))\\] ${clock}  ${GRYF}${LA}${GRYB}\\[$(tput el)\\]"
	ps1_2_l="${BLKB}${GRYF}${RA}\\[$(tput sgr0)\\]"
	PS1="${ps1_1_l}${ps1_1_r}\\r\\n${ps1_2_l}"
	PS2="${ps1_2_l}"
	PS4="${ps1_1_l}${ps1_1_r}\\r\\n${ps1_2_l}"
	export PS1
	export PS2
	export PS4
}

function set_normal_prompt() {
	local REDF YELF GREF BLUF PURF
	local usrin branch venv path ps1a ps1b
	DIRTY_SYM='*'
	CLEAN_SYM=''
	STASH_SYM='S'
	AHEAD_SYM='A'
	BHIND_SYM='B'

	REDF="\\[$(tput setaf  1)\\]"
	YELF="\\[$(tput setaf  3)\\]"
	GREF="\\[$(tput setaf 10)\\]"
	BLUF="\\[$(tput setaf 12)\\]"
	PURF="\\[$(tput setaf 13)\\]"

	# Display Username
	usrin="${REDF}{${GREF}\\h${REDF}}"

	# GIT STUFF
	if [ -d .git ] || git rev-parse --get-dir > /dev/null 2>&1
	then
		local _ahead _behind _dirty _branch _stash _status
		_ahead=$(git rev-list "@{u}..HEAD" | wc -l)
		_behind=$(git rev-list "HEAD..@{u}" | wc -l)
		_stash=$(git stash list | wc -l)
		_dirty=$(git status --porcelain | wc -l)
		_branch=$(git symbolic-ref HEAD 2>/dev/null)
		_status=${_branch#refs/heads/} # apparently faster than sed
		if (( _dirty > 0 ))
		then
			_status="$_status${REDF} $_dirty${DIRTY_SYM} "
		else
			_status="$_status${GREF}${CLEAN_SYM} "
		fi
		if (( _stash > 0 )); then
			_status="$_status${_stash}${STASH_SYM}"
		fi
		if (( _ahead > 0 )); then 
			_status="$_status${_ahead}${AHEAD_SYM}"
		fi
		if (( _behind > 0 )); then
			_status="$_status${_behind}${BHIND_SYM}"
		fi
		branch="${REDF}[${YELF}${_status}${REDF}]"
	else
		branch=""
	fi

	# Virtual Env stuff
	if [[ $VIRTUAL_ENV != "" ]]; then
		local _venv=${VIRTUAL_ENV##*/}
		venv="${REDF}(${PURF}${_venv}${REDF})"
	else
		venv=""
	fi

	path="${REDF}<${BLUF}\\w ${REDF}>"

	ps1a="${REDF}┌─${usrin}${branch}${venv}${path}"
	ps1b="${REDF}└─>\\[$(tput sgr0)\\]"
	PS1="${ps1a}\\r\\n${ps1b}"
	PS2="$ps1b"
	export PS1
	export PS2
}

function set_prompt() {
	use_powerline=$(( 1 ))
	if (( use_powerline )); then
		export PROMPT_COMMAND=set_powerline_prompt
	else
		export PROMPT_COMMAND=set_normal_prompt
	fi
}

set_prompt
