#!/bin/bash
# Prompt function because PROMPT_COMMAND is awesome

function set_powerline_prompt() {
	local RA REDF BLKF BLKB GREF GREB YELF YELB PRPF PRPB BLUF BLUB
	local usrin branch venv path ps1a ps1b
	RA=' '

	BLKF="\\[$(tput setaf  0)\\]"
	BLKB="\\[$(tput setab  0)\\]"
	REDF="\\[$(tput setaf  1)\\]"
	GREF="\\[$(tput setaf  2)\\]"
	GREB="\\[$(tput setab  2)\\]"
	YELF="\\[$(tput setaf  3)\\]"
	YELB="\\[$(tput setab  3)\\]"
	BLUF="\\[$(tput setaf  4)\\]"
	BLUB="\\[$(tput setab  4)\\]"
	PRPF="\\[$(tput setaf  5)\\]"
	PRPB="\\[$(tput setab  5)\\]"

	# Display Username
	usrin="${GREB}${BLKF} \\h  ${GREF}"

	# GIT STUFF
	if [ -d .git ] || git rev-parse --get-dir > /dev/null 2>&1
	then
		local _ahead _behind _dirty _branch _stash _status
		_ahead=$(git rev-list "@{u}..HEAD" | wc -l)
		_behind=$(git rev-list "HEAD..@{u}" | wc -l)
		_stash=$(git stash list | wc -l)
		_dirty=$(git status --porcelain | wc -l)
		_branch=$(git symbolic-ref HEAD 2>/dev/null)
		_status=${_branch#refs/heads/} # apparently faster than sed
		if (( _dirty > 0 ))
		then
			_status="$_status${REDF} $_dirty✗"
		else
			_status="$_status${GREF}✓"
		fi
		if (( _stash > 0 )); then
			_status="$_status${_stash}☐"
		fi
		if (( _ahead > 0 )); then 
			_status="$_status${_ahead}↑"
		fi
		if (( _behind > 0 )); then
			_status="$_status${_behind}↓"
		fi
		branch="${YELB}${RA}${BLKF} ${_status} ${YELF}"
	else
		branch=""
	fi

	# Virtual Env stuff
	if [[ $VIRTUAL_ENV != "" ]]; then
		local _venv=${VIRTUAL_ENV##*/}
		venv="${PRPB}${RA}${BLKF} ${_venv}  ${PRPF}"
	else
		venv=""
	fi

	path="${BLUB}${RA}${BLKF} \\w  ${BLUF}"

	ps1a="\\[$(tput hpa 0)\\]${usrin}${branch}${venv}${path} ${BLKB}${RA} "
	ps1b="${BLKB}${GREF}${RA}\\[$(tput sgr0)\\]"
	PS1="${ps1a}\\r\\n${ps1b}"
	PS2="${ps1b}"
	export PS1
	export PS2
}

function set_normal_prompt() {
	local REDF YELF GREF BLUF PURF
	local usrin branch venv path ps1a ps1b

	REDF="\\[$(tput setaf  1)\\]"
	YELF="\\[$(tput setaf  3)\\]"
	GREF="\\[$(tput setaf 10)\\]"
	BLUF="\\[$(tput setaf 12)\\]"
	PURF="\\[$(tput setaf 13)\\]"

	# Display Username
	usrin="${REDF}{${GREF}\\h${REDF}}"

	# GIT STUFF
	if [ -d .git ] || git rev-parse --get-dir > /dev/null 2>&1
	then
		local _branch _dirty
		_dirty=$(git status --porcelain | wc -l)
		if (( _dirty > 0 ))
		then
			dirty=""
		else
			dirty="*"
		fi
		_branch=$(git symbolic-ref HEAD 2>/dev/null)
		_branch=${_branch#refs/heads/} # apparently faster than sed
		branch="${REDF}[${YELF}${_branch}${REDF}${dirty}]"
	else
		branch=""
	fi
	# Virtual Env stuff
	if [[ $VIRTUAL_ENV != "" ]]; then
		local _venv=${VIRTUAL_ENV##*/}
		venv="${REDF}(${PURF}${_venv}${REDF})"
	else
		venv=""
	fi

	path="${REDF}<${BLUF}\\w ${REDF}>"

	ps1a="${REDF}┌─${usrin}${branch}${venv}${path}"
	ps1b="${REDF}└─>\\[$(tput sgr0)\\]"
	PS1="${ps1a}\\r\\n${ps1b}"
	PS2="$ps1b"
	export PS1
	export PS2
}

function set_prompt() {
	use_powerline=$(( 1 ))
	if (( use_powerline )); then
		export PROMPT_COMMAND=set_powerline_prompt
	else
		export PROMPT_COMMAND=set_normal_prompt
	fi
}

set_prompt
