#! /bin/bash
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -lh'
alias ls='ls --color=auto'
#alias make="global_make"

function latest(){
   A=(${@})
   prog=$1;
   lat=$(find . -type f -printf "%C@ %p\n" | sort | tail -n 1 | cut -d " " -f 2-)
   if [ ! -z "$2" ] ; then 
     args=${A[*]:1}; 
     $prog "$lat" "$args"
   else
     $prog "$lat"
   fi
}


activate_func() {
	if [[ $1 == */ ]]
	then
		source "${1}bin/activate"
	else
		source "${1}/bin/activate"
	fi
	alias pm="python manage.py"
}
alias activate="activate_func"

global_make() {
	if [ -e "GNUmakefile" ] || [ -e "makefile" ] || [ -e "Makefile" ] ; then
		make -j "$@"
	elif  [[ $PWD == *"/home/mkarpoff/UVa"* ]]; then
		echo "Making using UVa makefile"
		/usr/bin/make -f /home/mkarpoff/UVa/Support/Makefile "$*"
	else
		make --file=~/.global_makefile "$@"
	fi
}
# enable custom prompt
if [ -f ~/.bash_ps1 ]; then
    . ~/.bash_ps1
fi
