export PERSONAL_ACCOUNT='760030034999'
if [ -f $HOME/.config/zsh/zsh_ps1 ]; then
	source $HOME/.config/zsh/zsh_ps1
fi
export EDITOR=vim
export CLICOLOR=1

alias ls="ls --color=auto"
alias la="ls -a"
alias grep="grep --color=auto"
alias register_with_aaa="/apollo/env/AAAWorkspaceSupport/bin/register_with_aaa.py"


# brazil config
if [ -f $HOME/.config/brazil/rc ]; then
	source $HOME/.config/brazil/rc
fi

# bark config
if [ -f $HOME/.config/bark/rc ]; then
	source $HOME/.config/bark/rc
fi

# Enable vim-mode
export KEYTIMEOUT=20
bindkey -v
bindkey 'jk' vi-cmd-mode
bindkey '^[[Z' reverse-menu-complete

if [[ "$PATH" != *"$HOME/.local/bin/"* ]]; then
  export PATH="$HOME/.local/bin/:$PATH"
fi
