
if [ -f $HOME/.zsh_ps1 ]; then
	source $HOME/.zsh_ps1
fi
export EDITOR=vim
export CLICOLOR=1
export PATH="$HOME/.local/bin:$PATH"

alias la="ls -a"
alias ll="ls -l"
alias grep="grep -G"

# Enable vim-mode
bindkey -v
bindkey 'jk' vi-cmd-mode
bindkey '^[[Z' reverse-menu-complete

# Enable reverse search
bindkey '^R' history-incremental-search-backward


# Brazil Aliases
if [ -f "$HOME/.config/brazil/rc" ]; then
	source $HOME/.config/brazil/rc
fi

# VPN Aliases
if [ -f "$HOME/.config/vpn/rc" ]; then
	source $HOME/.config/vpn/rc
fi


if [[ "$PATH" != *"$HOME/.local/bin/"* ]]; then
	if [ -d "$HOME/.local/bin/" ]; then
		export PATH="$HOME/.local/bin/:$PATH"
	fi
fi

if [[ "$PATH" != *"$HOME/.toolbox/bin/"* ]]; then
	if [ -d "$HOME/.toolbox/bin/" ]; then
		export PATH="$HOME/.toolbox/bin/:$PATH"
	fi
fi

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

declare SSH_CERT="$HOME/.ssh/id_rsa-cert.pub"
